name: Renovate
on:
  schedule:
    - cron: "0/15 * * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}
          owner: ${{ github.repository_owner }}
          repositories: "WebSite"

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.3
        with:
          configurationFile: renovate-config.js
          token: "${{ steps.get_token.outputs.token }}"
